SegreteriaInventario/inventario/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^local/', views.showLocalDB, name='showLocalDB'),
    url(r'^inventario$', views.showLocalDB, name='showLocalDB'),
    # url(r'^remote/', views.showRemoteDB, name='showRemoteDB'),
    url(r'^update/partial', views.checkUpdate, name='checkUpdate'),
    url(r'^update/complete', views.updateLocalDB, name='updateLocalDB'),
    url(r'^show/([0-9]+)/$', views.showSingleItem, name='showSingleItem'),
    url(r'^table/getData', views.getData, name='getData'),
    url(r'^table/advancedSearch$', views.advancedSearch, name='advancedSearch'),
    url(r'^table/editable/editAccurateLocation', views.editAccurateLocation, name='editAccurateLocation'),
    url(r'^table/editable/getAccurateLocationList', views.getAccurateLocationList, name='getAccurateLocationList'),
    url(r'^table/editable/addAccurateLocation', views.addAccurateLocation, name='addAccurateLocation'),  
    url(r'^accounts/login/$', views.login, {'template_name': 'registration/login.html'}, name = 'login'),
	url(r'^upload/immagine$', views.uploadPicture),
    url(r'^ricinv/create$', views.ricognizioneInventarialeCreateView,name='ricinv_add'),
    url(r'^ricinv/createNoLabel$', views.ricognizioneInventarialeCreateNoLabelView,name='ricinv_add_no_label'),
	url(r'^ricinv/edit/', views.ricognizioneInventarialeEditView,name='ricinv_edit'),
    url(r'^ricinv/editNoLabel/', views.ricognizioneInventarialeEditNoLabelView,name='ricinv_edit_no_label'),
    url(r'^ricinv/delete/', views.ricognizioneInventarialeDeleteView,name='ricinv_delete'),
    url(r'^ricinv/getBeniForRicInve/$', views.getBeniForRicInve, name='getBeniForRicInve'),
    url(r'^ricinv/getPossessori/$', views.getPossessori, name='getPossessori'),
	url(r'^ricinv$', views.ricinv, name='ricinv'),
    url(r'^table/getRicognizioniData', views.getRicognizioniData, name='getRicognizioniData'),
    url(r'^table/advancedRicognizioneInventarialeSearch$', views.advancedRicognizioneInventarialeSearch, name='advancedRicognizioneInventarialeSearch'),
    url(r'^esse3user-autocomplete/$', views.Esse3UserAutocomplete.as_view(), name='esse3user-autocomplete'),
    url(r'^update/esse3users', views.updateLocalEsse3Users, name='updateLocalEsse3Users'),
    url(r'^update/codInvent', views.updateCodiciInventario, name='updateCodiciInventario'),
    url(r'^update/addCodInvent', views.addCodiceInventario, name='addCodiceInventario'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SegreteriaInventario/prova/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^local/', views.showLocalDB, name='showLocalDB'),
    url(r'^remote/', views.showRemoteDB, name='showRemoteDB'),
    url(r'^update/partial', views.checkUpdate, name='checkUpdate'),
    url(r'^update/complete', views.updateLocalDB, name='updateLocalDB'),
    url(r'^show/([0-9]+)/$', views.showSingleItem, name='showSingleItem'),
    url(r'^examples/bootstrap_table/data', views.getData, name='getData'),
    url(r'^examples/bootstrap_table_editable/editAccurateLocation', views.editAccurateLocation, name='editAccurateLocation'),
    url(r'^examples/bootstrap_table_editable/getAccurateLocationList', views.getAccurateLocationList, name='getAccurateLocationList'),
    url(r'^examples/bootstrap_table_editable/addAccurateLocation', views.addAccurateLocation, name='addAccurateLocation'),  
    url(r'^accounts/login/$', views.login, {'template_name': 'registration/login.html'}, name = 'login'),
    url(r'^accounts/registration/$', views.registration),
	url(r'^upload/$', views.uploadPicture),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SegreteriaInventario/inventario/models.py
from django.db import models

from django.contrib.auth.models import User

class UbicazionePrecisa(models.Model):
	ubicazione = models.CharField(max_length=2000)

	def __str__(self):		# __unicode__ on Python 2
		return self.ubicazione

class Inventario(models.Model):
    cd_invent = models.CharField(max_length=8, primary_key=True)
    ds_invent = models.CharField(max_length=256)

    def __str__(self):      # __unicode__ on Python 2
        return u' '.join((self.cd_invent," - ", self.ds_invent)).encode('utf-8').strip()

class Bene(models.Model):
    id_bene = models.IntegerField(default=None)
    cd_invent = models.CharField(max_length=8)
    ds_invent = models.CharField(max_length=256,default=None)
    pg_bene = models.IntegerField(default=None)
    pg_bene_sub = models.IntegerField(default=None)
    ds_bene = models.CharField(max_length=400)
    dt_registrazione_buono = models.DateTimeField('data registrazione buono')
    cd_categ_gruppo = models.CharField(max_length=60)
    ds_categ_gruppo = models.CharField(max_length=255)
    ds_spazio = models.CharField(max_length=2000)
    ubicazione_precisa = models.ForeignKey(UbicazionePrecisa, null=True, on_delete=models.SET_NULL)
    dt_ini_ammortamento = models.DateTimeField('data inizio ammortamento')
    valore_convenzionale = models.DecimalField(max_digits=15, decimal_places=2)
    nome_tipo_dg = models.CharField(max_length=128,default=None)
    num_doc_rif = models.CharField(max_length=128,default=None)
    num_registrazione = models.IntegerField(default=None)
    dt_registrazione_dg =models.IntegerField('anno di registrazione documento',default=None)
    denominazione = models.CharField(max_length=256,default=None)
    nome = models.CharField(max_length=128,default=None, null = True)
    cognome = models.CharField(max_length=128,default=None, null = True)
    immagine = models.FileField(upload_to='pictures/%Y/%m/%d', null=True)

class RicognizioneInventariale(models.Model):
    ds_bene = models.CharField(max_length=400, default="")
    possessore = models.CharField(max_length=100, default=None)
    nuovo_possessore = models.CharField(max_length=100,default=None, blank=True, null=True)
    inserito_da = models.ForeignKey(User, default=None, related_name='ricinv_inseritori', blank=True, null=True)
    inventario = models.ForeignKey(Inventario, default=None, blank=True, null=True, on_delete=models.SET_NULL)
    pg_bene = models.IntegerField(default=-1, blank=True, null=True)
    pg_bene_sub = models.IntegerField(default=-1, blank=True, null=True)
    ds_spazio = models.CharField(max_length=2000, default=None)
    ubicazione_precisa = models.ForeignKey(UbicazionePrecisa,blank=True, null=True, on_delete=models.SET_NULL)
    note = models.CharField(max_length=400, blank=True, null=True)
    immagine = models.FileField(upload_to='pictures/%Y/%m/%d', blank=True, null=True)
    nome = models.CharField(max_length=128,default=None, null = True)
    cognome = models.CharField(max_length=128,default=None, null = True)

class Esse3User(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)

SegreteriaInventario/inventario/views.py
from django.shortcuts import render
from django.template import RequestContext, loader
from django.http import HttpResponse, HttpResponseServerError
from django.http import JsonResponse
from django.db import connections
from django.db.models import Q
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib.auth.views import login as django_auth_login
from django.views.generic.edit import CreateView

from models import Bene, UbicazionePrecisa, RicognizioneInventariale

from forms import PictureForm, RicognizioneInventarialeForm, AdvancedSearchForm, AdvancedSearchRicognizioneInventarialeForm

from dal import autocomplete
from models import Inventario
from models import Esse3User 

#from django.forms import ChoiceField,ModelForm
from django.forms.widgets import Select

import datetime
import json
from django.core import serializers
from django.http import JsonResponse

from django.contrib.auth import authenticate, login

import logging

@login_required
def index(request):
	# return showLocalDB(request)

    return render (request,'inventario/index.html')

def ricinv(request):
	return showRicognizioniInventariali(request)

@never_cache
def login(request, *args, **kw):
    logger = logging.getLogger('django_auth_ldap')
    logger.addHandler(logging.StreamHandler())
    logger.setLevel(logging.DEBUG)
    if request.method == 'POST':
        user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
        if(user):
            try:
                user.first_name = user.username.split('.')[0]
                user.last_name = user.username.split('.')[1]
                user.save()
            except IndexError:
                pass
        return django_auth_login(request, *args, **kw)
    if request.method == 'GET':
        return django_auth_login(request, *args, **kw)

# prende il cursore che ha eseguito la query, estrae i risultati sotto
# forma di dizionario che ha come chiave il nome del campo
def rows_to_dict_list(cursor):
    columns = [i[0] for i in cursor.description]
    return [dict(zip(columns, row)) for row in cursor]


@login_required
def showRemoteDB(request):

    cursor = connections['cineca'].cursor()

    cursor.execute(
    	"SELECT *\
    	FROM (\
	    	SELECT \
		    	INV.ID_INVENTARIO_BENI,\
		    	INV.DS_BENE,\
		    	MOV.DT_REGISTRAZIONE_BUONO,\
		    	INV.VALORE_CONVENZIONALE,\
		    	SPA.DS_SPAZIO,\
		    	INV.DT_INI_AMMORTAMENTO,\
                INV.VALORE_CONVENZIONALE - \
                (LEAST((extract(year from sysdate) - EXTRACT(year FROM INV.DT_INI_AMMORTAMENTO)),AMM.NUM_ANNUALITA) * \
                    (INV.VALORE_CONVENZIONALE / AMM.NUM_ANNUALITA)) AS VALORE_RESIDUO\
	    	FROM\
	    		(((V_IE_CO_MOVIMENTI_BENE MOV INNER JOIN V_IE_CO_INVENTARIO_BENI INV\
	    		ON MOV.ID_INVENTARIO_BENI = INV.ID_INVENTARIO_BENI) INNER JOIN\
	    		V_IE_AC_SPAZI SPA ON INV.CD_UBICAZIONE = SPA.CD_SPAZIO) INNER JOIN\
                V_IE_CO_AS_TIP_AMM_CAT_GRP_INV AMM on INV.CD_CATEG_GRUPPO = AMM.CD_CATEG_GRUPPO )\
	    	ORDER BY\
	    		MOV.ID_INVENTARIO_BENI DESC\
    		)\
        WHERE\
            rownum < 100"
    	)

    rows = rows_to_dict_list(cursor)

    context = {'rows': rows}

    return render (request,'inventario/inventarioRemoto.html',context)



@login_required
def showLocalDB(request):

    picform = PictureForm()  # costruisce una form per l'upload dell'immagine
    asform = AdvancedSearchForm()  # costruisce una form per l'upload dell'immagine
    # prende le location dal DB per popolare il menu della quicksearch
    locations = Bene.objects.using('default').values_list('ds_spazio', flat=True).distinct()
    locations = filter(None, locations)
    locations = [l.split('-')[0].lower() for l in locations]
    locations = sorted(locations)
    # prende le accurateLocation dal DB per popolare il menu della quicksearch
    accurateLocations = UbicazionePrecisa.objects.using('default').all().order_by('ubicazione')
    possessori = Bene.objects.using('default').exclude(nome=None).values_list('nome','cognome').distinct()
    possessori = filter(None, possessori)
    possessori = sorted(possessori)

    codici_inventario = Bene.objects.using('default').order_by('cd_invent').values_list('cd_invent', 'ds_invent').distinct()
    codici_inventario = filter(None, codici_inventario)
    lista_codici = dict()
# metto i codici in una lista
    for c in codici_inventario:
        lista_codici[c[0]] = c[1]
        
    context = {
        'locations': locations, 
        'accurateLocations': accurateLocations, 
        'picform': picform, 
        'asform': asform, 
        'possessori': possessori,
        'lista_codici' : lista_codici,
    }
    return render (request,'inventario/inventarioLocale.html',context)

@login_required
def updateLocalEsse3Users(request):
    cursor = connections['cineca'].cursor()         # Cursor connessione Cineca
    cursorLocal = connections['default'].cursor()   # Cursor DB locale
    # Seleziona tutti i dati necessari dal DB remoto
    cursor.execute(
        "SELECT DISTINCT\
                ACAB.NOME,\
                ACAB.COGNOME\
        FROM\
                V_IE_AC_AB_ALL ACAB\
        GROUP BY\
                ACAB.NOME,\
                ACAB.COGNOME"
        )

    rows = rows_to_dict_list(cursor)

    for row in rows:
        # Per ogni riga vede se l'oggetto esiste gia' nel database
        try:
            #print "obj ",row['ID_INVENTARIO_BENI'],"val res: ",row['VALORE_RESIDUO']
            esse3user = Esse3User.objects.get(name=row['NOME'],surname=row['COGNOME'])

            # Se l'oggetto esiste i dati vengono aggiornati
        except Esse3User.DoesNotExist:
            # Se non esiste viene creato un nuovo oggetto
            name = row['NOME']
            surname = row['COGNOME']

            #esse3user = Esse3User(name = name,
            #            surname = surname) 
            #esse3user.save()
            print name, " ", surname

    return HttpResponse("creati %s utenti di esse3" % len(rows))

@login_required
def updateLocalDB(request):
    cursor = connections['cineca'].cursor()         # Cursor connessione Cineca
    cursorLocal = connections['default'].cursor()   # Cursor DB locale
    


    # Seleziona tutti i dati necessari dal DB remoto
    cursor.execute(
        "SELECT DISTINCT\
                INV.ID_INVENTARIO_BENI,\
                INV.CD_INVENT,\
                CD_INV.DS_INVENT,\
                INV.PG_BENE,\
                INV.PG_BENE_SUB,\
                INV.DS_BENE,\
                MOV.DT_REGISTRAZIONE_BUONO,\
                INV.CD_CATEG_GRUPPO,\
                GRP.DS_CATEG_GRUPPO,\
                SPA.DS_SPAZIO,\
                INV.DT_INI_AMMORTAMENTO,\
                INV.VALORE_CONVENZIONALE,\
                MOV.AMM_IVA_DETR,\
                MOV.AMM_IVA_INDETR,\
                DG02.NOME_TIPO_DG,\
                DG02.NUM_DOC_RIF,\
                DG02.NUM_REGISTRAZIONE,\
                EXTRACT(year FROM DG02.DT_REGISTRAZIONE) DT_REGISTRAZIONE_YEAR,\
                ACAB.DENOMINAZIONE,\
                ACAB2.NOME,\
                ACAB2.COGNOME\
        FROM\
                ((((((((((SIACO_UNICAM_PROD.V_IE_CO_INVENTARIO_BENI INV\
                INNER JOIN SIACO_UNICAM_PROD.V_IE_CO_MOVIMENTI_BENE MOV\
                ON INV.ID_INVENTARIO_BENI = MOV.ID_INVENTARIO_BENI)\
                INNER JOIN V_IE_AC_NODI_AB NODI\
                on MOV.uo_numerante=NODI.cd_nodo)\
                INNER JOIN V_IE_DG02_DG DG02\
                on MOV.num_registrazione_dg = DG02.num_registrazione and NODI.id_ab=DG02.id_uo_origine\
                and MOV.tipo_dg=DG02.nome_tipo_dg and extract(year from MOV.dt_registrazione_buono) = DG02.anno_rif)\
                INNER JOIN SIACO_UNICAM_PROD.V_IE_CO_CATEG_GRP_INVENT GRP\
                ON INV.CD_CATEG_GRUPPO = GRP.CD_CATEG_GRUPPO)\
                INNER JOIN SIACO_UNICAM_PROD.V_IE_AC_SPAZI SPA\
                ON INV.CD_UBICAZIONE = SPA.CD_SPAZIO)\
                INNER JOIN V_IE_AC_AB_ALL ACAB\
                ON INV.ID_FORNITORE = ACAB.ID_AB)\
                INNER JOIN V_IE_DG02_DG_DETT DG02_DETT\
                ON DG02.ID_DG = DG02_DETT.ID_DG)\
                INNER JOIN V_IE_DG24_X_INVE DG24\
                ON DG24.NR_RIGA=DG02_DETT.NR_RIGA AND DG02_DETT.ID_DG_DETT=DG24.ID_DG_DETT)\
                LEFT JOIN V_IE_AC_AB_ALL ACAB2\
                ON DG24.ID_AB_POSSESSORE = ACAB2.ID_AB)\
                INNER JOIN V_IE_CO_INVENTARIO CD_INV\
                ON INV.CD_INVENT=CD_INV.CD_INVENT)\
        ORDER BY\
                INV.ID_INVENTARIO_BENI ASC"
        )

    rows = rows_to_dict_list(cursor)
   
    ids = set()
    to_remove = set()
    for row in rows:
        if row['ID_INVENTARIO_BENI'] in ids:
            to_remove.add(row['ID_INVENTARIO_BENI'])
        ids.add(row['ID_INVENTARIO_BENI'])

    print("len1: %s" % len(rows))

    for row in rows:
        if row['ID_INVENTARIO_BENI'] in to_remove:
            rows.remove(row)

    print("len2: %s" % len(rows))

    # Scorre tutti i dati riga per riga
    for row in rows:
        # Per ogni riga vede se l'oggetto esiste gia' nel database
        try:
            #print "obj ",row['ID_INVENTARIO_BENI'],"val res: ",row['VALORE_RESIDUO']
            bene = Bene.objects.get(id_bene=row['ID_INVENTARIO_BENI'])

            # Se l'oggetto esiste i dati vengono aggiornati
            
            bene.id_bene = row['ID_INVENTARIO_BENI'] if row['ID_INVENTARIO_BENI'] is not None else -1
            bene.cd_invent = row['CD_INVENT'] if row['CD_INVENT'] is not None else ''
            bene.ds_invent = row['DS_INVENT'] if row['DS_INVENT'] is not None else ''
            bene.pg_bene = row['PG_BENE'] if row['PG_BENE'] is not None else -1
            bene.pg_bene_sub = row['PG_BENE_SUB'] if row['PG_BENE_SUB'] is not None else -1

SegreteriaInventario/inventario/templates/inventario/RicognizioneInventariale/create.html
{% load widget_tweaks %}
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="createRicInvModalLabel">
            {% block modal-title %}
            Ricognizione Inventariale
            {% endblock %}
        </h4>
      </div>
      <div class="modal-body">
        <div class="tabbable">
            <ul id="ricinv_form_tabs" class="nav nav-tabs" data-tabs="tabs">
                <li id="tabLabel" class="active mytabs">
                    <a href="#One" data-toggle="tab">Con Etichetta</a>
                </li>
                <li id="tabNoLabel" class="mytabs">
                    <a href="#Two" data-toggle="tab">Senza Etichetta</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="One">
                    {% block form-header %}
                    <form name="ricinv_form" id="tabLabel-form" method="POST" action="{% url "inventario.views.ricognizioneInventarialeCreateView" %}" enctype="multipart/form-data">
                    {% endblock %} 
                        {% csrf_token %}
                        <!-- descrizione bene -->
                        <p>{{ form.ds_bene.errors }}</p>
                        <div class="col-xs-12"><p>{{ form.ds_bene.label_tag }}<a class="text-left text-danger"><b>*</b></a>{{ form.ds_bene.help_text }}{% render_field form.ds_bene class+="form-control edit_ds_bene required"%}</p></div>

                        <!-- possessore -->
                        <p>{{ form.possessore.errors }}</p>
                        <div class="col-xs-12">
                                 <p>{{ form.possessore.label_tag }}<a class="text-left text-danger"><b>*</b></a>
                                    {{ form.possessore.help_text }}
                                     <div class="input-group">
                                        {% render_field form.possessore class+="form-control autocomplete_possessore edit_possessore required" %}
                                     <span class="input-group-btn">
                                          <button id="id_btn_nuovo_possessore" class="btn btn-default" type="button" title="Nuovo Possessore">
                                              <span class="glyphicon glyphicon-user"></span>&nbsp;
                                          </button>
                                     </span>
                                    </div>
                                </p>
                        </div>

                        <!-- nuovo nuovo_possessore -->
                        <p>{{ form.nuovo_possessore.errors }}</p>
                        <div class="col-xs-12" id="div_id_nuovo_possessore"><p>{{ form.nuovo_possessore.label_tag }} {{ form.nuovo_possessore.help_text }}{% render_field form.nuovo_possessore class+="form-control autocomplete_possessore edit_nuovo_possessore" %}</p></div>

                        <!-- inseritore -->
                        <p>{{ form.inserito_da.errors }}</p>
                        <div class="col-xs-12"><p>{{ form.inserito_da.label_tag }}{{ form.inserito_da.help_text }}{% render_field form.inserito_da class+="form-control edit_inserito_da" %}</p></div>

                        <!-- inventario -->
                        <p>{{ form.inventario.errors }}</p>
                        <div class="col-xs-12"><p>{{ form.inventario.label_tag }}<a class="text-left text-danger"><b>*</b></a>{{ form.inventario.help_text }}{% render_field form.inventario class+="form-control required edit_inventario" %}</p></div>

                        <!-- numero inventario e bene collegato -->
                        <div class="col-xs-12"><p>
                            <p>{{ form.pg_bene.errors }}</p>
                            <p>{{ form.pg_bene_sub.errors }}</p>
                            <p>{{ form.pg_bene.help_text }}</p>
                            <p>{{ form.pg_bene_sub.help_text }}</p>
                            <label for="id_pg_bene">Numero inventario e bene collegato:</label><a class="text-left text-danger"><b>*</b></a>
                            <div class="input-group">
                                {% render_field form.pg_bene class+="form-control col-xs-9 edit_pg_bene required" placeholder+="numero inventario" %}
                                <span class="input-group-addon">-</span>
                                {% render_field form.pg_bene_sub class+="form-control col-xs-3 edit_pg_bene_sub required" placeholder+="bene collegato" %}
                            </div>
                        </p></div>

                        <!-- ds_spazio -->
                        <p>{{ form.ds_spazio.errors }}</p>
                        <div class="col-xs-12"><p>{{ form.ds_spazio.label_tag }}<a class="text-left text-danger"><b>*</b></a>{{ form.ds_spazio.help_text }}{% render_field form.ds_spazio class+="form-control edit_ds_spazio required" %}</p></div>
                        <!-- ubicazione_precisa -->
                        <p>{{ form.ubicazione_precisa.errors }}</p>
                        <div class="col-xs-12"><p>{{ form.ubicazione_precisa.label_tag }}{{ form.ubicazione_precisa.help_text }}{% render_field form.ubicazione_precisa class+="form-control edit_ubicazione_precisa" %}</p></div>
                        <!-- note -->
                        <div class="col-xs-12" >
                          <p>
                              <p>{{ form.note.errors }}</p>
                              <p>{{ form.note.label_tag }} {{ form.note.help_text }} {% render_field form.note class+="form-control edit_note" %}</p>
                          </p>
                        </div>
                        <!-- immagine -->
                        <div class="col-xs-12" >
                            <p>{{ form.non_field_errors }}</p>
                            <p>{{ form.immagine.label_tag }} {{ form.immagine.help_text }}</p>
                            <p>
                                {{ form.immagine.errors }}
                                <span class="btn btn-primary btn-file">
                                    Scegli un Immagine... {{ form.immagine }}
                                </span>
                            </p>
                        </div>
                        <input type="submit" style="visibility: hidden;" />
                    </form>
                </div>
                <div class="tab-pane" id="Two">
                    <form name="ricinv_form" id="tabNoLabel-form" method="POST" action="{% url "inventario.views.ricognizioneInventarialeCreateNoLabelView" %}" enctype="multipart/form-data"> 
                        {% csrf_token %}
                        <!-- descrizione bene -->
                        <p>{{ form.ds_bene.errors }}</p>
                        <div class="col-xs-12"><p>{{ form.ds_bene.label_tag }}<a class="text-left text-danger"><b>*</b></a>{{ form.ds_bene.help_text }}{% render_field form.ds_bene class+="form-control edit_ds_bene required"%}</p></div>

                        <!-- possessore -->
                        <p>{{ form.possessore.errors }}</p>
                        <div class="col-xs-12">
                                 <p>{{ form.possessore.label_tag }}<a class="text-left text-danger"><b>*</b></a>
                                    {{ form.possessore.help_text }}
                                    {% render_field form.possessore class+="form-control autocomplete_possessore edit_possessore required" %}
                                </p>
                        </div>

                        <!-- ds_spazio -->
                        <p>{{ form.ds_spazio.errors }}</p>
                        <div class="col-xs-12"><p>{{ form.ds_spazio.label_tag }}<a class="text-left text-danger"><b>*</b></a>{{ form.ds_spazio.help_text }}{% render_field form.ds_spazio class+="form-control edit_ds_spazio required" %}</p></div>
                        <!-- ubicazione_precisa -->
                        <p>{{ form.ubicazione_precisa.errors }}</p>
                        <div class="col-xs-12"><p>{{ form.ubicazione_precisa.label_tag }}{{ form.ubicazione_precisa.help_text }}{% render_field form.ubicazione_precisa class+="form-control edit_ubicazione_precisa" %}</p></div>
                        <!-- note -->
                        <div class="col-xs-12" >
                          <p>
                              <p>{{ form.note.errors }}</p>
                              <p>{{ form.note.label_tag }} {{ form.note.help_text }} {% render_field form.note class+="form-control edit_note" %}</p>
                          </p>
                        </div>
                        <!-- immagine -->
                        <div class="col-xs-12" >
                            <p>{{ form.non_field_errors }}</p>
                            <p>{{ form.immagine.label_tag }} {{ form.immagine.help_text }}</p>
                            <p>
                                {{ form.immagine.errors }}
                                <span class="btn btn-primary btn-file">
                                    Scegli un Immagine... {{ form.immagine }}
                                </span>
                            </p>
                        </div>
                        <input type="submit" style="visibility: hidden;" />
                    </form>
                </div>
            </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
        <button id="save-button" type="button" class="btn btn-primary">Crea</button>
      </div>
    </div>
</div>

SegreteriaInventario/inventario/templates/inventario/RicognizioneInventariale/delete.html
{% load widget_tweaks %}
<div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">
                {% block modal-title %}
                Rimuovi Ricognizione Inventariale
                {% endblock %}
            </h4>
        </div>
        <div class="modal-body">
            {% block form-header %}
            <form name="ricinv_form" id="ricinv_delete_form_id" method="POST" action="{% url "inventario.views.ricognizioneInventarialeDeleteView" %}">    
                {% endblock %}                        
                {% csrf_token %}
                Sei sicuro di voler continuare?
            </form>
        </div>
        <div class="modal-footer">
            {% block submit-button %}
            <input id="delete_submit_btn_id" type="submit" class="btn btn-danger" value="Elimina"/>
            {% endblock %}
            <button type="button" class="btn btn-default" data-dismiss="modal">Annulla</button>
        </div>
    </div>
</div>

SegreteriaInventario/inventario/templates/inventario/RicognizioneInventariale/edit.html
{% extends "inventario/RicognizioneInventariale/create.html" %}
{% load widget_tweaks %}

{% block modal-title %}
Modifica Ricognizione Inventariale
{% endblock %}

{% block form-header %}
<form name="ricinv_edit_form" id="ricinv_edit_form_id" method="POST" action="{% url "inventario.views.ricognizioneInventarialeEditView" %}" enctype="multipart/form-data">    
{% endblock %}